spring:
  sql:
    init:
      platform: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/post
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000

