spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      enabled: true
logging:
  level:
    pers.clare: debug

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    env:
      enabled: true
    mappings:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true
      show-details: always
    configprops:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full
